"""QSC graticule and eclipse-path SVG utilities."""

from .cgrcs import (
    FACE_CODES,
    ISO_VIEWS,
    SYSTEM_VERSION,
    CubePoint,
    GeoPoint,
    GraticuleCell,
    ReferenceFrame,
    RhombAddress,
    cgrcs_manifest,
    enumerate_reference_frames,
    enumerate_rhomb_addresses,
    geo_to_vector,
    get_visible_faces,
    graticule_cell_face_xy,
    graticule_cell_index,
    graticule_cell_lonlat_ring,
    make_reference_frame,
    make_rhomb_address,
    project_lonlat_ring_to_face_xy,
    project_lonlat_to_cube,
    project_to_cube,
    reference_frame_from_offset,
    reference_frame_from_projection_offset,
    split_at_cube_seams,
    unproject_from_cube,
    vector_to_geo,
)
from .cells import (
    CellId,
    adjacent_cells,
    all_cells,
    cell_at_face_xy,
    cell_at_lonlat,
    cell_label,
    cell_ring_face_xy,
    cell_ring_lonlat,
    cells_for_face,
)
from .geometry import (
    FACE_NAMES,
    FacePoint,
    ProjectionOffset,
    face_xy_to_lonlat,
    face_xy_to_pixel,
    lonlat_to_face_xy,
    oriented_lonlat_to_vec3,
    oriented_vec3_to_lonlat,
    pixel_to_face_xy,
)
from .paths import cells_intersecting_face_polygon, cells_intersecting_geojson
from .sandbox import export_tile_sandbox_zip
from .saros import get_eclipse, load_saros
from .svg import CLASSIC_CROSS_LAYOUT, render_face_net_svg, render_face_svg, render_iso_face_svg, render_iso_svg
from .view import (
    IsoView,
    best_iso_view_for_cells,
    best_iso_view_for_eclipse,
    render_best_iso_eclipse_svg,
    render_best_iso_saros_svg,
    visible_faces_for_corner,
)


__all__ = [
    "CellId",
    "CubePoint",
    "FACE_CODES",
    "FACE_NAMES",
    "FacePoint",
    "GeoPoint",
    "GraticuleCell",
    "ISO_VIEWS",
    "IsoView",
    "ProjectionOffset",
    "ReferenceFrame",
    "RhombAddress",
    "SYSTEM_VERSION",
    "CLASSIC_CROSS_LAYOUT",
    "adjacent_cells",
    "all_cells",
    "best_iso_view_for_cells",
    "best_iso_view_for_eclipse",
    "cgrcs_manifest",
    "cell_at_face_xy",
    "cell_at_lonlat",
    "cell_label",
    "cell_ring_face_xy",
    "cell_ring_lonlat",
    "cells_for_face",
    "cells_intersecting_face_polygon",
    "cells_intersecting_geojson",
    "enumerate_reference_frames",
    "enumerate_rhomb_addresses",
    "face_xy_to_lonlat",
    "face_xy_to_pixel",
    "export_tile_sandbox_zip",
    "geo_to_vector",
    "get_eclipse",
    "get_visible_faces",
    "graticule_cell_face_xy",
    "graticule_cell_index",
    "graticule_cell_lonlat_ring",
    "load_saros",
    "lonlat_to_face_xy",
    "make_reference_frame",
    "make_rhomb_address",
    "oriented_lonlat_to_vec3",
    "oriented_vec3_to_lonlat",
    "pixel_to_face_xy",
    "project_lonlat_ring_to_face_xy",
    "project_lonlat_to_cube",
    "project_to_cube",
    "reference_frame_from_offset",
    "reference_frame_from_projection_offset",
    "render_best_iso_eclipse_svg",
    "render_best_iso_saros_svg",
    "render_face_net_svg",
    "render_face_svg",
    "render_iso_face_svg",
    "render_iso_svg",
    "split_at_cube_seams",
    "unproject_from_cube",
    "vector_to_geo",
    "visible_faces_for_corner",
]
